name: crdt
description: Dart implementation of Conflict-free Replicated Data Types (CRDTs).
version: 6.0.0
homepage: https://github.com/cachapa/crdt
repository: https://github.com/cachapa/crdt
issue_tracker: https://github.com/cachapa/crdt/issues

environment:
  sdk: ^3.10.0

dependencies:
  meta: any
  uuid: ^4.5.3

dev_dependencies:
  lints: any
  test: any
