name: hive_crdt
description: A CRDT backed by a Hive store.
version: 1.0.0
homepage: https://github.com/cachapa/crdt

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  crdt:
    path: ../
  hive: ^1.4.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.7
  uuid: ^2.0.0
